import os
import time
import numpy as np
import soundfile as sf
import gradio as gr
from groq import Groq

# --- SETUP ---
groq_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

system_prompt = """You are a medical scribe assistant.
Convert a doctor-patient transcript into a structured SOAP note.

Rules:
- Output ONLY the SOAP note. No explanations.
- Preserve all medical facts: symptoms, durations, dosages, drug names.
- Correct obvious misspellings of drug names (e.g., "penadol" -> "Paracetamol").
- Use clinical language, not conversational language.
- If a section has no information, write "Not documented."
- Never invent facts that weren't in the transcript.

Format:
SUBJECTIVE:
[Patient's reported symptoms, duration, history]

OBJECTIVE:
[Vitals, exam findings - if mentioned]

ASSESSMENT:
[Clinical impression]

PLAN:
[Medications, tests, follow-up]
"""


def generate_note(audio_file, progress=gr.Progress()):
    if audio_file is None:
        return "Please upload or record audio.", "", "", "", ""

    time.sleep(0.5)
    sample_rate, audio_data = audio_file

    if audio_data is None or len(audio_data) == 0:
        return "No audio detected. Please try again.", "", "", "", ""

    progress(0.1, desc="Processing audio...")

    if len(audio_data.shape) > 1:
        audio_data = audio_data.mean(axis=1)

    if audio_data.dtype != np.float32:
        audio_data = audio_data.astype(np.float32) / np.iinfo(audio_data.dtype).max

    temp_path = "/tmp/audio.wav"
    sf.write(temp_path, audio_data, sample_rate)

    progress(0.3, desc="Transcribing...")
    with open(temp_path, "rb") as f:
        transcription = groq_client.audio.transcriptions.create(
            file=("audio.wav", f.read()),
            model="whisper-large-v3-turbo",
            language="ur",
            response_format="text"
        )
    transcript = transcription if isinstance(transcription, str) else transcription.text

    if not transcript.strip():
        return "No speech detected. Please try again.", "", "", "", ""

    progress(0.6, desc="Generating medical note...")
    response = groq_client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Convert this transcript:\n\n{transcript}"}
        ],
        temperature=0.1
    )
    soap_note = response.choices[0].message.content

    sections = {"S": "", "O": "", "A": "", "P": ""}
    current = None
    for line in soap_note.split("\n"):
        upper = line.strip().upper()
        if upper.startswith("SUBJECTIVE"):
            current = "S"
        elif upper.startswith("OBJECTIVE"):
            current = "O"
        elif upper.startswith("ASSESSMENT"):
            current = "A"
        elif upper.startswith("PLAN"):
            current = "P"
        elif current:
            sections[current] += line + "\n"

    progress(1.0, desc="Done")

    return (
        transcript,
        sections["S"].strip(),
        sections["O"].strip(),
        sections["A"].strip(),
        sections["P"].strip()
    )


def check_audio_ready(audio):
    if audio is None:
        return gr.update(interactive=False)
    sample_rate, audio_data = audio
    if audio_data is None or len(audio_data) == 0:
        return gr.update(interactive=False)
    return gr.update(interactive=True)


custom_css = """
.gradio-container {
    max-width: 900px !important;
    margin: auto !important;
    font-family: 'Inter', -apple-system, sans-serif !important;
}
.header-box {
    text-align: center;
    padding: 20px 0 10px 0;
}
.header-box h1 {
    font-size: 34px;
    font-weight: 800;
    margin-bottom: 4px;
    color: #1a1a2e;
    letter-spacing: -0.5px;
}
.header-box .logo {
    font-size: 28px;
    margin-right: 6px;
}
.header-box p {
    color: #666;
    font-size: 15px;
    margin-top: 0;
}
.generate-btn {
    background: #2563eb !important;
    color: white !important;
    border: none !important;
    font-weight: 600 !important;
    font-size: 16px !important;
    padding: 12px !important;
    border-radius: 8px !important;
}
.generate-btn:hover {
    background: #1d4ed8 !important;
}
"""


def compile_note(subj, obj, assess, plan):
    note = f"""SCRIBEO — MEDICAL NOTE
{'=' * 50}

SUBJECTIVE:
{subj or 'Not documented.'}

OBJECTIVE:
{obj or 'Not documented.'}

ASSESSMENT:
{assess or 'Not documented.'}

PLAN:
{plan or 'Not documented.'}

{'=' * 50}
Generated by Scribeo
For demo purposes only — always verify with a licensed clinician.
"""
    return note


def save_note(subj, obj, assess, plan):
    content = compile_note(subj, obj, assess, plan)
    file_path = "/tmp/scribeo_note.txt"
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)
    return file_path


with gr.Blocks(title="Scribeo", theme=gr.themes.Soft()) as demo:

    gr.HTML("""
        <div class="header-box">
            <h1><span class="logo">🩺</span>Scribeo</h1>
            <p>Convert Urdu-English doctor-patient conversations into structured medical notes.</p>
        </div>
    """)

    with gr.Group():
        audio_input = gr.Audio(
            type="numpy",
            label="Upload or record a conversation",
            sources=["upload", "microphone"]
        )

    generate_btn = gr.Button(
        "Generate Note",
        variant="primary",
        interactive=False,
        elem_classes="generate-btn"
    )

    with gr.Tabs():
        with gr.Tab("📋 Medical Note"):
            gr.Markdown(
                "<div style='color: #666; font-size: 13px; margin-bottom: 8px;'>"
                "✏️ You can edit any section below before saving."
                "</div>"
            )
            with gr.Row():
                subjective = gr.Textbox(label="Subjective", info="Patient reported", lines=6, interactive=True, scale=1)
                objective = gr.Textbox(label="Objective", info="Doctor observed", lines=6, interactive=True, scale=1)
                assessment = gr.Textbox(label="Assessment", info="Clinical impression", lines=6, interactive=True, scale=1)
                plan = gr.Textbox(label="Plan", info="Medications, follow-up", lines=6, interactive=True, scale=1)

            download_btn = gr.DownloadButton(
                label="⬇️ Download Note",
                value=None,
                variant="secondary"
            )

        with gr.Tab("📝 Raw Transcript"):
            transcript_box = gr.Textbox(label="Transcribed conversation", lines=10, interactive=True)

    gr.Markdown(
        "<div style='text-align: center; color: #999; font-size: 13px; margin-top: 20px;'>"
        "Scribeo · Powered by Whisper + LLM · For demo purposes only — always verify with a licensed clinician."
        "</div>"
    )

    audio_input.change(check_audio_ready, inputs=[audio_input], outputs=[generate_btn])
    generate_btn.click(generate_note, inputs=[audio_input], outputs=[transcript_box, subjective, objective, assessment, plan])
    download_btn.click(save_note, inputs=[subjective, objective, assessment, plan], outputs=[download_btn])


if __name__ == "__main__":
    demo.launch(server_name="0.0.0.0", server_port=int(os.environ.get("PORT", 7860)))